name: pipeline
on: 
  workflow_dispatch:
    inputs:
      path:
        description: 'build path'     
        required: true
        default: 'foo/bar'
      tags:
        description: 'my tag'  
# on: [push, pull_request]
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    steps:
      - name: Hello world
        shell: bash
        run: |
          echo "Hello World"
          cat /etc/os-release

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: moondev/machine-images
      #     path: ctr/kind
      #     tag: v1.19.1-rc.0
      #     # tag_with_ref: true
      #     # tag_with_sha: true
